version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    privileged: true
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    hostname: leyou
